version: "3.9"
services:
  autoheal:
    restart: on-failure
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build:
      context: ./server
      args:
        NODE_ENV: development

    depends_on:
      - postgresql
    restart: on-failure

    env_file: server/.env

    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

    tty: true
    #  /run/secrets/db_password
    environment:
      - DB_HOST=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=mypassword
      - DB_NAME=postgres
      - NODE_ENV=development

    command: npm run dev

    ports:
      - 5000:5000

    networks:
      - app

    secrets:
      - db_password

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    tty: true
    restart: on-failure
    networks:
      - app
    depends_on:
      - backend

  postgresql:
    image: postgres
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    networks:
      - app

    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: postgres

  nginx:
    image: nginx:1.21.5-alpine

    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  db-data:
secrets:
  db_password:
    file: db_password.txt
